# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
container: meai1/llvmcone:llvm8

steps:
- script: |
    echo "$USER"
    sudo echo "$USER"
    echo `ls -la` /root/llvm8
  displayName: 'check if this is the right container'

- script: |
    git clone https://github.com/Meai1/cone
    mkdir cone/build && cd cone/build
    cmake ..
    sudo make -j4
  displayName: 'cone build'

- script: |
    echo '$(Pipeline.Workspace)'
    ls -R $(Pipeline.Workspace)
  displayName: 'check Pipeline.Workspace'

- script: |
    echo $(Agent.BuildDirectory)
    ls -R $(Agent.BuildDirectory)
  displayName: 'check Agent.BuildDirectory'

- script: |
    echo $(Build.SourcesDirectory)
    ls -R $(Build.SourcesDirectory)
  displayName: 'check Build.SourcesDirectory'

- script: |
    echo '$(Build.ArtifactStagingDirectory)'
    ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'check Build.ArtifactStagingDirectory'


- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.BuildDirectory)
    contents: '**/cone/conec' 
    flattenFolders: true
    targetFolder: $(Build.ArtifactStagingDirectory)
  

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/conec'
    artifact: 'conec-binary'

